/**
 * ZIP Renderer for Evidence Packs
 * Bundles JSON, PDF, and manifest into a ZIP archive
 */

import archiver from 'archiver';
import { Writable } from 'stream';
import type { EvidencePack } from './types.js';
import { renderPdf } from './renderPdf.js';

/**
 * Render an evidence pack as a ZIP archive buffer
 * Contains: evidence.json, evidence.pdf, manifest.txt
 */
export async function renderZip(pack: EvidencePack): Promise<Buffer> {
    return new Promise(async (resolve, reject) => {
        try {
            const chunks: Buffer[] = [];

            // Create a writable stream that collects chunks
            const writableStream = new Writable({
                write(chunk, _encoding, callback) {
                    chunks.push(chunk);
                    callback();
                },
            });

            const archive = archiver('zip', {
                zlib: { level: 9 }, // Maximum compression
            });

            archive.on('error', reject);

            writableStream.on('finish', () => {
                resolve(Buffer.concat(chunks));
            });

            archive.pipe(writableStream);

            // Add JSON file
            const jsonContent = JSON.stringify(pack, null, 2);
            archive.append(jsonContent, { name: 'evidence.json' });

            // Add PDF file
            const pdfBuffer = await renderPdf(pack);
            archive.append(pdfBuffer, { name: 'evidence.pdf' });

            // Add manifest file
            const manifestContent = [
                'EVIDENCE PACK MANIFEST',
                '======================',
                '',
                `Listing ID: ${pack.subject.listing.id}`,
                `Title: ${pack.subject.listing.title}`,
                `Generated: ${pack.meta.generated_at}`,
                `Generated By: ${pack.meta.generated_by.role} (${pack.meta.generated_by.actor_id_redacted})`,
                '',
                'FILES',
                '-----',
                '- evidence.json: Complete machine-readable evidence pack',
                '- evidence.pdf: Human-readable summary document',
                '- manifest.txt: This file',
                '',
                'INTEGRITY',
                '---------',
                `Pack Hash (SHA-256): ${pack.integrity.pack_hash}`,
                `Timeline Hash Chain: ${pack.integrity.timeline_hash_chain}`,
                '',
                'ROW COUNTS',
                '----------',
                `- Audit Log Entries: ${pack.integrity.row_count.audit_log}`,
                `- Reviews: ${pack.integrity.row_count.reviews}`,
                `- Viewings: ${pack.integrity.row_count.viewings}`,
                '',
                'VERIFICATION',
                '------------',
                'To verify integrity:',
                '1. Parse evidence.json',
                '2. Remove integrity.pack_hash field',
                '3. Compute SHA-256 of the remaining JSON (canonical form)',
                '4. Compare with pack_hash above',
                '',
                'LEGAL NOTICE',
                '------------',
                'This evidence pack contains redacted personal information.',
                'For unredacted data, contact the system administrator with',
                'appropriate legal authorization.',
                '',
                `Schema Version: ${pack.meta.schema_version}`,
                `Timezone: ${pack.meta.timezone}`,
            ].join('\n');

            archive.append(manifestContent, { name: 'manifest.txt' });

            await archive.finalize();
        } catch (err) {
            reject(err);
        }
    });
}
