insert into public.property_feed_sources (name, url, category, active)
values
  ('Property Market', 'https://propertymarket.com.mt', 'marketplace', true),
  ('MaltaPark', 'https://maltapark.com', 'marketplace', true),
  ('Darscover', 'https://darscover.com', 'marketplace', true),
  ('Idealista Malta', 'https://www.idealista.com/mt', 'marketplace', true),
  ('Yitaku', 'https://yitaku.com', 'marketplace', true),
  ('RE/MAX Malta', 'https://www.remax-malta.com', 'agency', true),
  ('Frank Salt', 'https://franksalt.com.mt', 'agency', true),
  ('Dhalia', 'https://dhalia.com', 'agency', true),
  ('Alliance', 'https://www.alliance.mt', 'agency', true),
  ('Zanzi Homes', 'https://zanzihomes.com', 'agency', true),
  ('QuickLets', 'https://quicklets.com.mt', 'agency', true),
  ('Belair Property', 'https://belair.com.mt', 'agency', true),
  ('Simon Mamo', 'https://simonmamo.com', 'agency', true),
  ('Ben Estates', 'https://benestates.com', 'agency', true),
  ('Century 21 Malta', 'https://www.century21.mt', 'agency', true),
  ('Malta Sothebys Realty', 'https://maltasothebysrealty.com', 'luxury', true),
  ('Perry', 'https://www.perry.com.mt', 'luxury', true),
  ('Engel and Volkers Malta', 'https://ev-malta.com', 'luxury', true),
  ('Excel Homes', 'https://excel.com.mt', 'luxury', true),
  ('Northern Properties', 'https://www.np.com.mt', 'regional', true),
  ('Gozo Prime', 'https://gozoprime.com', 'regional', true),
  ('Lea Properties', 'https://leaproperties.com', 'regional', true),
  ('77 Great Estates', 'https://77greatestates.com', 'regional', true),
  ('Short Lets Malta', 'https://shortletsmalta.com', 'short-let', true),
  ('Baron Holiday Homes', 'https://baronholidayhomes.com', 'short-let', true),
  ('Zzzing', 'https://zzzing.com', 'short-let', true),
  ('Happy Rentals Malta', 'https://www.happy.rentals/malta', 'short-let', true),
  ('Easy Landlord', 'https://easylandlord.com', 'short-let', true),
  ('Holiday Malta', 'https://holidaymalta.com', 'short-let', true),
  ('No Agent Fees', 'https://noagentfees.com.mt', 'direct-owner', true),
  ('Properties From Owner', 'https://propertiesfromowner.com', 'direct-owner', true),
  ('Homes In Malta', 'https://homesinmalta.com', 'direct-owner', true),
  ('QLC Commercial', 'https://qlc.com.mt', 'commercial', true),
  ('Office in Malta', 'https://officeinmalta.com', 'commercial', true),
  ('AX Hotels', 'https://axhotelsmalta.com', 'hotel-group', true),
  ('db Hotels', 'https://dbhotelsresorts.com', 'hotel-group', true),
  ('Corinthia', 'https://www.corinthia.com', 'hotel-group', true),
  ('IK Collection', 'https://ikcollection.com', 'hotel-group', true),
  ('Hilton Malta', 'https://www.hilton.com', 'hotel-luxury', true),
  ('Westin Dragonara', 'https://westinmalta.com', 'hotel-luxury', true),
  ('InterContinental Malta', 'https://malta.intercontinental.com', 'hotel-luxury', true),
  ('Malta Marriott', 'https://www.marriott.com', 'hotel-luxury', true),
  ('Radisson Blu Malta', 'https://www.radissonhotels.com', 'hotel-luxury', true),
  ('Hyatt Regency Malta', 'https://www.hyatt.com', 'hotel-luxury', true),
  ('Kempinski Gozo', 'https://www.kempinski.com', 'hotel-luxury', true),
  ('The Phoenicia', 'https://www.phoeniciamalta.com', 'hotel-boutique', true),
  ('Iniala Harbour House', 'https://www.inialamalta.com', 'hotel-boutique', true),
  ('The Xara Palace', 'https://xarapalace.com.mt', 'hotel-boutique', true),
  ('Casa Ellul', 'https://casaellul.com', 'hotel-boutique', true),
  ('The Embassy Valletta', 'https://embassyvallettahotel.com', 'hotel-boutique', true),
  ('Grand Hotel Excelsior', 'https://excelsior.com.mt', 'hotel-boutique', true),
  ('Domus Zamittello', 'https://domuszamittello.com', 'hotel-boutique', true),
  ('Hugos Hotels', 'https://hugoshotels.com', 'hotel-boutique', true),
  ('Hotel Valentina', 'https://hotelvalentina.com', 'hotel-boutique', true),
  ('Hotel Juliani', 'https://hoteljuliani.com', 'hotel-boutique', true),
  ('Verdi Hotels', 'https://verdihotels.com', 'hotel-boutique', true),
  ('Lure Hotel and Spa', 'https://lurehotelmalta.com', 'hotel-resort', true),
  ('Solana Hotel', 'https://solanahotel.com', 'hotel-resort', true),
  ('Paradise Bay Hotel', 'https://paradise-bay.com', 'hotel-resort', true),
  ('Duke Boutique Hotel', 'https://thedukeboutiquehotel.com', 'hotel-resort', true),
  ('Ta Cenc and Spa', 'https://tacenc.com', 'hotel-resort', true),
  ('Facebook Marketplace Rentals', 'https://www.facebook.com/marketplace/category/propertyrentals', 'facebook', true),
  ('Facebook Marketplace Sales', 'https://www.facebook.com/marketplace/category/propertysale', 'facebook', true),
  ('Accommodation Malta Group', 'https://www.facebook.com/groups/accommodationmalta', 'facebook-group', true),
  ('Direct From Owner Malta', 'https://www.facebook.com/groups/DirectFromOwnerMalta', 'facebook-group', true),
  ('Rent Direct From Owner Malta', 'https://www.facebook.com/groups/rentdirectfromownermalta', 'facebook-group', true),
  ('Gozo Property Group', 'https://www.facebook.com/groups/gozoproperty', 'facebook-group', true),
  ('Expats Malta Property', 'https://www.facebook.com/groups/expatsmalta.property', 'facebook-group', true),
  ('MaltaPlaza Classifieds', 'https://www.facebook.com/groups/MaltaPlaza', 'facebook-group', true),
  ('Find Property Malta', 'https://www.facebook.com/groups/whatroof', 'facebook-group', true)
on conflict (url) do update
  set name = excluded.name,
      category = excluded.category,
      active = true,
      updated_at = now();
